CLASSES = UnaryFunction.class ShiftFunction.class TableFunction.class RestoredTableFunction.class InterferometerFunction.class BinaryFunction.class Shift1Function2.class Shift2Function2.class DiffFunction.class DiffFunction2.class TableFunction2.class RestoredTableFunction2.class Interferometer1Function2.class Interferometer2Function2.class Test.class

all: $(CLASSES)

%.class: %.java
	javac $<
